package cli

import (
	"fmt"
	"sort"
	"strings"
)

// cmdInternalComplete is invoked by the shell completion scripts to
// fetch candidate snippet keys for the current prefix. Output is one
// key per line, sorted. Errors are silenced (return 0 with no output)
// so completion never spews into the user's terminal.
func (a *App) cmdInternalComplete(args []string) int {
	prefix := ""
	if len(args) > 0 {
		prefix = args[0]
	}
	f, _, err := a.load()
	if err != nil {
		return 0
	}
	var keys []string
	for _, s := range f.Snippets {
		if strings.HasPrefix(s.Key, prefix) {
			keys = append(keys, s.Key)
		}
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintln(a.out(), k)
	}
	return 0
}

func (a *App) cmdCompletion(args []string) int {
	if len(args) < 1 {
		return a.usage("usage: pe completion <bash|zsh|fish>")
	}
	switch args[0] {
	case "bash":
		fmt.Fprint(a.out(), bashCompletion)
	case "zsh":
		fmt.Fprint(a.out(), zshCompletion)
	case "fish":
		fmt.Fprint(a.out(), fishCompletion)
	default:
		return a.usage("unsupported shell: %s (use bash, zsh, or fish)", args[0])
	}
	return 0
}

const bashCompletion = `# bash completion for pe — generated by ` + "`pe completion bash`" + `
# install:  pe completion bash > ~/.local/share/bash-completion/completions/pe
_pe() {
    local cur cmd
    cur="${COMP_WORDS[COMP_CWORD]}"
    cmd="${COMP_WORDS[1]:-}"

    if [ "$COMP_CWORD" -eq 1 ]; then
        local subs="a add l list ls s search find e edit d delete rm show help version completion"
        local keys
        keys="$(pe __complete "$cur" 2>/dev/null)"
        COMPREPLY=( $(compgen -W "${subs} ${keys}" -- "$cur") )
        return
    fi

    case "$cmd" in
        e|edit|d|delete|rm|\?|show)
            local keys
            keys="$(pe __complete "$cur" 2>/dev/null)"
            COMPREPLY=( $(compgen -W "$keys" -- "$cur") )
            ;;
        completion)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
            ;;
    esac
}
complete -F _pe pe
`

const zshCompletion = `#compdef pe
# zsh completion for pe — generated by ` + "`pe completion zsh`" + `
# install (one-liner):
#   pe completion zsh > "${fpath[1]}/_pe"
# or to a user dir on fpath:
#   mkdir -p ~/.zsh/completions
#   pe completion zsh > ~/.zsh/completions/_pe
#   echo 'fpath=(~/.zsh/completions $fpath)' >> ~/.zshrc
#   echo 'autoload -Uz compinit && compinit' >> ~/.zshrc
_pe() {
    local cur cmd
    cur="${words[CURRENT]}"
    cmd="${words[2]:-}"

    if (( CURRENT == 2 )); then
        local subs=(a add l list ls s search find e edit d delete rm '?' show help version completion)
        local keys=("${(@f)$(pe __complete "$cur" 2>/dev/null)}")
        compadd -- "${subs[@]}"
        compadd -- "${keys[@]}"
        return
    fi

    case "$cmd" in
        e|edit|d|delete|rm|'?'|show)
            local keys=("${(@f)$(pe __complete "$cur" 2>/dev/null)}")
            compadd -- "${keys[@]}"
            ;;
        completion)
            compadd -- bash zsh fish
            ;;
    esac
}
compdef _pe pe
`

const fishCompletion = `# fish completion for pe — generated by ` + "`pe completion fish`" + `
# install:  pe completion fish > ~/.config/fish/completions/pe.fish
function __pe_keys
    pe __complete (commandline -ct) 2>/dev/null
end

function __pe_no_subcmd
    set -l cmd (commandline -opc)
    if test (count $cmd) -eq 1
        return 0
    end
    return 1
end

function __pe_seen_key_subcmd
    set -l cmd (commandline -opc)
    if test (count $cmd) -lt 2
        return 1
    end
    switch $cmd[2]
        case e edit d delete rm '?' show
            return 0
    end
    return 1
end

complete -c pe -f
complete -c pe -n '__pe_no_subcmd' -a 'a add l list ls s search find e edit d delete rm \\? show help version completion'
complete -c pe -n '__pe_no_subcmd' -a '(__pe_keys)' -d 'snippet'
complete -c pe -n '__pe_seen_key_subcmd' -a '(__pe_keys)' -d 'snippet'
complete -c pe -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'
`
